package com.atguigu.atcrowdfunding.mapper;


import com.atguigu.atcrowdfunding.entity.Admin;
import com.atguigu.atcrowdfunding.entity.AdminExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Feb 05 21:47:38 CST 2021
     */
    int countByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Feb 05 21:47:38 CST 2021
     */
    int deleteByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Feb 05 21:47:38 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Feb 05 21:47:38 CST 2021
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Feb 05 21:47:38 CST 2021
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Feb 05 21:47:38 CST 2021
     */
    List<Admin> selectByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Feb 05 21:47:38 CST 2021
     */
    Admin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Feb 05 21:47:38 CST 2021
     */
    int updateByExampleSelective(@Param("record") Admin record, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Feb 05 21:47:38 CST 2021
     */
    int updateByExample(@Param("record") Admin record, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Feb 05 21:47:38 CST 2021
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Feb 05 21:47:38 CST 2021
     */
    int updateByPrimaryKey(Admin record);

    List<Admin> queryAdminListByCondition(@Param("queryCondition") String queryCondition);

    int updateAdminById(Admin admin);

    /**
     * 逻辑删除
     * @param adminId
     * @return
     */
    int logicDeleteAdminById(Integer adminId);

    /**
     * 逻辑批量删除
     * @param adminIds
     * @return
     */
    int batchLogicDeleteAdminById(@Param("adminIds") String[] adminIds);

    /**
     * 逻辑查询
     * @return
     */
    List<Admin> logicSelectAdminList();


    /**
     * 带条件的逻辑查询
     * @param queryCondition
     * @return
     */
    List<Admin> logicSelectAdminListByCondition(String queryCondition);
}